sudo: required
language: generic
services:
  - docker
install:
  - echo "pre-test installs go here"
script:
  - docker --version
  - docker build -t digirati/brilleaux:latest .
after_success:
  - echo "successful build!"
