sudo: required
language: generic
services:
  - docker
before_install:
  - docker --version
  - docker build -t digirati/brilleaux:latest .
script:
  - echo "run tests here!"
after_success:
  - echo "successful build!"
  - docker push digirati/brilleaux:latest
